use crate::ffi::*;
use crate::util::media;
use crate::utils;
#[cfg(feature = "serialize")]
use serde::{Deserialize, Serialize};

#[allow(non_camel_case_types)]
#[derive(Eq, PartialEq, Clone, Copy, Debug)]
#[cfg_attr(feature = "serialize", derive(Serialize, Deserialize))]
pub enum Id {
    None,

    // video codecs
    MPEG1VIDEO,
    MPEG2VIDEO,
    #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
    MPEG2VIDEO_XVMC,
    H261,
    H263,
    RV10,
    RV20,
    MJPEG,
    MJPEGB,
    LJPEG,
    SP5X,
    JPEGLS,
    MPEG4,
    RAWVIDEO,
    MSMPEG4V1,
    MSMPEG4V2,
    MSMPEG4V3,
    WMV1,
    WMV2,
    H263P,
    H263I,
    FLV1,
    SVQ1,
    SVQ3,
    DVVIDEO,
    HUFFYUV,
    CYUV,
    H264,
    INDEO3,
    VP3,
    THEORA,
    ASV1,
    ASV2,
    FFV1,
    XM4,
    VCR1,
    CLJR,
    MDEC,
    ROQ,
    INTERPLAY_VIDEO,
    XAN_WC3,
    XAN_WC4,
    RPZA,
    CINEPAK,
    WS_VQA,
    MSRLE,
    MSVIDEO1,
    IDCIN,
    BPS8,
    SMC,
    FLIC,
    TRUEMOTION1,
    VMDVIDEO,
    MSZH,
    ZLIB,
    QTRLE,
    TSCC,
    ULTI,
    QDRAW,
    VIXL,
    QPEG,
    PNG,
    PPM,
    PBM,
    PGM,
    PGMYUV,
    PAM,
    FFVHUFF,
    RV30,
    RV40,
    VC1,
    WMV3,
    LOCO,
    WNV1,
    AASC,
    INDEO2,
    FRAPS,
    TRUEMOTION2,
    BMP,
    CSCD,
    MMVIDEO,
    ZMBV,
    AVS,
    SMACKVIDEO,
    NUV,
    KMVC,
    FLASHSV,
    CAVS,
    JPEG2000,
    VMNC,
    VP5,
    VP6,
    VP6F,
    TARGA,
    DSICINVIDEO,
    TIERTEXSEQVIDEO,
    TIFF,
    GIF,
    DXA,
    DNXHD,
    THP,
    SGI,
    C93,
    BETHSOFTVID,
    PTX,
    TXD,
    VP6A,
    AMV,
    VB,
    PCX,
    SUNRAST,
    INDEO4,
    INDEO5,
    MIMIC,
    RL2,
    ESCAPE124,
    DIRAC,
    BFI,
    CMV,
    MOTIONPIXELS,
    TGV,
    TGQ,
    TQI,
    AURA,
    AURA2,
    V210X,
    TMV,
    V210,
    DPX,
    MAD,
    FRWU,
    FLASHSV2,
    CDGRAPHICS,
    R210,
    ANM,
    BINKVIDEO,
    IFF_ILBM,
    IFF_BYTERUN1,
    KGV1,
    YOP,
    VP8,
    PICTOR,
    ANSI,
    A64_MULTI,
    A64_MULTI5,
    R10K,
    MXPEG,
    LAGARITH,
    PRORES,
    JV,
    DFA,
    WMV3IMAGE,
    VC1IMAGE,
    UTVIDEO,
    BMV_VIDEO,
    VBLE,
    DXTORY,
    V410,
    XWD,
    CDXL,
    XBM,
    ZEROCODEC,
    MSS1,
    MSA1,
    TSCC2,
    MTS2,
    CLLC,
    MSS2,
    VP9,
    AIC,
    ESCAPE130,
    G2M,
    WEBP,
    HNM4_VIDEO,
    HEVC,
    H265,
    FIC,
    ALIAS_PIX,
    BRENDER_PIX,
    PAF_VIDEO,
    EXR,
    VP7,
    SANM,
    SGIRLE,
    MVC1,
    MVC2,
    HQX,
    TDSC,
    HQ_HQA,
    HAP,
    DDS,
    DXV,
    SCREENPRESSO,
    RSCC,

    Y41P,
    AVRP,
    V012,
    AVUI,
    #[cfg(not(feature = "ffmpeg_7_0"))]
    AYUV,
    TARGA_Y216,
    V308,
    V408,
    YUV4,
    AVRN,
    CPIA,
    XFACE,
    SNOW,
    SMVJPEG,
    APNG,
    DAALA,
    CFHD,
    TRUEMOTION2RT,
    M101,
    MAGICYUV,
    SHEERVIDEO,
    YLC,

    // various PCM "codecs"
    PCM_S16LE,
    PCM_S16BE,
    PCM_U16LE,
    PCM_U16BE,
    PCM_S8,
    PCM_U8,
    PCM_MULAW,
    PCM_ALAW,
    PCM_S32LE,
    PCM_S32BE,
    PCM_U32LE,
    PCM_U32BE,
    PCM_S24LE,
    PCM_S24BE,
    PCM_U24LE,
    PCM_U24BE,
    PCM_S24DAUD,
    PCM_ZORK,
    PCM_S16LE_PLANAR,
    PCM_DVD,
    PCM_F32BE,
    PCM_F32LE,
    PCM_F64BE,
    PCM_F64LE,
    PCM_BLURAY,
    PCM_LXF,
    S302M,
    PCM_S8_PLANAR,
    PCM_S24LE_PLANAR,
    PCM_S32LE_PLANAR,
    PCM_S16BE_PLANAR,

    PCM_S64LE,
    PCM_S64BE,

    // various ADPCM codecs
    ADPCM_IMA_QT,
    ADPCM_IMA_WAV,
    ADPCM_IMA_DK3,
    ADPCM_IMA_DK4,
    ADPCM_IMA_WS,
    ADPCM_IMA_SMJPEG,
    ADPCM_MS,
    ADPCM_4XM,
    ADPCM_XA,
    ADPCM_ADX,
    ADPCM_EA,
    ADPCM_G726,
    ADPCM_CT,
    ADPCM_SWF,
    ADPCM_YAMAHA,
    ADPCM_SBPRO_4,
    ADPCM_SBPRO_3,
    ADPCM_SBPRO_2,
    ADPCM_THP,
    ADPCM_IMA_AMV,
    ADPCM_EA_R1,
    ADPCM_EA_R3,
    ADPCM_EA_R2,
    ADPCM_IMA_EA_SEAD,
    ADPCM_IMA_EA_EACS,
    ADPCM_EA_XAS,
    ADPCM_EA_MAXIS_XA,
    ADPCM_IMA_ISS,
    ADPCM_G722,
    ADPCM_IMA_APC,
    ADPCM_VIMA,

    ADPCM_AFC,
    ADPCM_IMA_OKI,
    ADPCM_DTK,
    ADPCM_IMA_RAD,
    ADPCM_G726LE,
    ADPCM_THP_LE,
    ADPCM_PSX,
    ADPCM_AICA,
    ADPCM_IMA_DAT4,
    ADPCM_MTAF,

    // AMR
    AMR_NB,
    AMR_WB,

    // RealAudio codecs
    RA_144,
    RA_288,

    // various DPCM codecs
    ROQ_DPCM,
    INTERPLAY_DPCM,
    XAN_DPCM,
    SOL_DPCM,

    SDX2_DPCM,

    // audio codecs
    MP2,
    MP3,
    AAC,
    AC3,
    DTS,
    VORBIS,
    DVAUDIO,
    WMAV1,
    WMAV2,
    MACE3,
    MACE6,
    VMDAUDIO,
    FLAC,
    MP3ADU,
    MP3ON4,
    SHORTEN,
    ALAC,
    WESTWOOD_SND1,
    GSM,
    QDM2,
    COOK,
    TRUESPEECH,
    TTA,
    SMACKAUDIO,
    QCELP,
    WAVPACK,
    DSICINAUDIO,
    IMC,
    MUSEPACK7,
    MLP,
    GSM_MS,
    ATRAC3,
    APE,
    NELLYMOSER,
    MUSEPACK8,
    SPEEX,
    WMAVOICE,
    WMAPRO,
    WMALOSSLESS,
    ATRAC3P,
    EAC3,
    SIPR,
    MP1,
    TWINVQ,
    TRUEHD,
    MP4ALS,
    ATRAC1,
    BINKAUDIO_RDFT,
    BINKAUDIO_DCT,
    AAC_LATM,
    QDMC,
    CELT,
    G723_1,
    G729,
    SVX_EXP8,
    SVX_FIB8,
    BMV_AUDIO,
    RALF,
    IAC,
    ILBC,
    OPUS,
    COMFORT_NOISE,
    TAK,
    METASOUND,
    PAF_AUDIO,
    ON2AVC,
    DSS_SP,

    CODEC2,
    FFWAVESYNTH,
    SONIC,
    SONIC_LS,
    EVRC,
    SMV,
    DSD_LSBF,
    DSD_MSBF,
    DSD_LSBF_PLANAR,
    DSD_MSBF_PLANAR,
    _4GV,
    INTERPLAY_ACM,
    XMA1,
    XMA2,
    DST,

    // subtitle codecs
    DVD_SUBTITLE,
    DVB_SUBTITLE,
    TEXT,
    XSUB,
    SSA,
    MOV_TEXT,
    HDMV_PGS_SUBTITLE,
    DVB_TELETEXT,
    SRT,

    MICRODVD,
    EIA_608,
    JACOSUB,
    SAMI,
    REALTEXT,
    STL,
    SUBVIEWER1,
    SUBVIEWER,
    SUBRIP,
    WEBVTT,
    MPL2,
    VPLAYER,
    PJS,
    ASS,
    HDMV_TEXT_SUBTITLE,

    // other specific kind of codecs (generally used for attachments)
    TTF,

    SCTE_35,
    BINTEXT,
    XBIN,
    IDF,
    OTF,
    SMPTE_KLV,
    DVD_NAV,
    TIMED_ID3,
    BIN_DATA,

    PROBE,

    MPEG2TS,
    MPEG4SYSTEMS,
    FFMETADATA,
    WRAPPED_AVFRAME,

    PSD,
    PIXLET,
    SPEEDHQ,
    CLEARVIDEO,
    FMVC,
    SCPR,
    XPM,
    AV1,
    PCM_F16LE,
    PCM_F24LE,
    ATRAC3AL,
    ATRAC3PAL,

    BITPACKED,
    MSCC,
    SRGC,
    SVG,
    GDV,
    FITS,
    GREMLIN_DPCM,
    DOLBY_E,

    APTX,
    APTX_HD,
    SBC,

    AVS2,
    IMM4,
    PROSUMER,
    MWSC,
    WCMV,
    RASC,
    PCM_VIDC,
    ATRAC9,
    TTML,

    HYMT,
    ARBC,
    AGM,
    LSCR,
    VP4,
    ADPCM_AGM,
    HCOM,
    ARIB_CAPTION,

    #[cfg(feature = "ffmpeg_4_3")]
    IMM5,
    #[cfg(feature = "ffmpeg_4_3")]
    MVDV,
    #[cfg(feature = "ffmpeg_4_3")]
    MVHA,
    #[cfg(feature = "ffmpeg_4_3")]
    CDTOONS,
    #[cfg(feature = "ffmpeg_4_3")]
    MV30,
    #[cfg(feature = "ffmpeg_4_3")]
    NOTCHLC,
    #[cfg(feature = "ffmpeg_4_3")]
    PFM,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_ARGO,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_SSI,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_ZORK,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_APM,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_ALP,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_MTF,
    #[cfg(feature = "ffmpeg_4_3")]
    ADPCM_IMA_CUNNING,
    #[cfg(feature = "ffmpeg_4_3")]
    DERF_DPCM,
    #[cfg(feature = "ffmpeg_4_3")]
    ACELP_KELVIN,
    #[cfg(feature = "ffmpeg_4_3")]
    MPEGH_3D_AUDIO,
    #[cfg(feature = "ffmpeg_4_3")]
    SIREN,
    #[cfg(feature = "ffmpeg_4_3")]
    HCA,
    #[cfg(feature = "ffmpeg_4_3")]
    EPG,

    #[cfg(feature = "ffmpeg_4_4")]
    AVS3,
    #[cfg(feature = "ffmpeg_4_4")]
    PGX,
    #[cfg(feature = "ffmpeg_4_4")]
    MSP2,
    #[cfg(feature = "ffmpeg_4_4")]
    VVC,
    #[cfg(feature = "ffmpeg_4_4")]
    MOBICLIP,
    #[cfg(feature = "ffmpeg_4_4")]
    PHOTOCD,
    #[cfg(feature = "ffmpeg_4_4")]
    ARGO,
    #[cfg(feature = "ffmpeg_4_4")]
    CRI,
    #[cfg(feature = "ffmpeg_4_4")]
    IPU,
    #[cfg(feature = "ffmpeg_4_4")]
    SIMBIOSIS_IMX,
    #[cfg(feature = "ffmpeg_4_4")]
    SGA_VIDEO,
    #[cfg(feature = "ffmpeg_4_4")]
    PCM_SGA,
    #[cfg(feature = "ffmpeg_4_4")]
    ADPCM_IMA_MOFLEX,
    #[cfg(feature = "ffmpeg_4_4")]
    FASTAUDIO,

    #[cfg(feature = "ffmpeg_5_0")]
    GEM,
    #[cfg(feature = "ffmpeg_5_0")]
    ADPCM_IMA_ACORN,
    #[cfg(feature = "ffmpeg_5_0")]
    MSNSIREN,

    #[cfg(feature = "ffmpeg_5_1")]
    VBN,
    #[cfg(feature = "ffmpeg_5_1")]
    JPEGXL,
    #[cfg(feature = "ffmpeg_5_1")]
    QOI,
    #[cfg(feature = "ffmpeg_5_1")]
    PHM,
    #[cfg(feature = "ffmpeg_5_1")]
    DFPWM,

    #[cfg(feature = "ffmpeg_6_0")]
    RADIANCE_HDR,
    #[cfg(feature = "ffmpeg_6_0")]
    WBMP,
    #[cfg(feature = "ffmpeg_6_0")]
    MEDIA100,
    #[cfg(feature = "ffmpeg_6_0")]
    VQC,
    #[cfg(feature = "ffmpeg_6_0")]
    ADPCM_XMD,
    #[cfg(feature = "ffmpeg_6_0")]
    WADY_DPCM,
    #[cfg(feature = "ffmpeg_6_0")]
    CBD2_DPCM,
    #[cfg(feature = "ffmpeg_6_0")]
    BONK,
    #[cfg(feature = "ffmpeg_6_0")]
    MISC4,
    #[cfg(feature = "ffmpeg_6_0")]
    APAC,
    #[cfg(feature = "ffmpeg_6_0")]
    FTR,
    #[cfg(feature = "ffmpeg_6_0")]
    WAVARC,
    #[cfg(feature = "ffmpeg_6_0")]
    RKA,
    #[cfg(feature = "ffmpeg_6_0")]
    VNULL,
    #[cfg(feature = "ffmpeg_6_0")]
    ANULL,

    #[cfg(feature = "ffmpeg_6_1")]
    PDV,
    #[cfg(feature = "ffmpeg_6_1")]
    EVC,
    #[cfg(feature = "ffmpeg_6_1")]
    RTV1,
    #[cfg(feature = "ffmpeg_6_1")]
    VMIX,
    #[cfg(feature = "ffmpeg_7_0")]
    LEAD,
    #[cfg(feature = "ffmpeg_6_1")]
    AC4,
    #[cfg(feature = "ffmpeg_6_1")]
    OSQ,
    #[cfg(feature = "ffmpeg_7_0")]
    QOA,
    #[cfg(feature = "ffmpeg_7_1")]
    LC3,
    #[cfg(feature = "ffmpeg_6_1")]
    SMPTE_2038,
    #[cfg(feature = "ffmpeg_7_1")]
    LCEVC,
}

impl Id {
    pub fn medium(&self) -> media::Type {
        unsafe { media::Type::from(avcodec_get_type((*self).into())) }
    }

    pub fn name(&self) -> &'static str {
        unsafe { utils::str_from_c_ptr(avcodec_get_name((*self).into())) }
    }
}

impl From<AVCodecID> for Id {
    fn from(value: AVCodecID) -> Self {
        use AVCodecID as AV;

        match value {
            AV::AV_CODEC_ID_NONE => Id::None,

            /* video codecs */
            AV::AV_CODEC_ID_MPEG1VIDEO => Id::MPEG1VIDEO,
            AV::AV_CODEC_ID_MPEG2VIDEO => Id::MPEG2VIDEO,
            #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
            AV::AV_CODEC_ID_MPEG2VIDEO_XVMC => Id::MPEG2VIDEO_XVMC,
            AV::AV_CODEC_ID_H261 => Id::H261,
            AV::AV_CODEC_ID_H263 => Id::H263,
            AV::AV_CODEC_ID_RV10 => Id::RV10,
            AV::AV_CODEC_ID_RV20 => Id::RV20,
            AV::AV_CODEC_ID_MJPEG => Id::MJPEG,
            AV::AV_CODEC_ID_MJPEGB => Id::MJPEGB,
            AV::AV_CODEC_ID_LJPEG => Id::LJPEG,
            AV::AV_CODEC_ID_SP5X => Id::SP5X,
            AV::AV_CODEC_ID_JPEGLS => Id::JPEGLS,
            AV::AV_CODEC_ID_MPEG4 => Id::MPEG4,
            AV::AV_CODEC_ID_RAWVIDEO => Id::RAWVIDEO,
            AV::AV_CODEC_ID_MSMPEG4V1 => Id::MSMPEG4V1,
            AV::AV_CODEC_ID_MSMPEG4V2 => Id::MSMPEG4V2,
            AV::AV_CODEC_ID_MSMPEG4V3 => Id::MSMPEG4V3,
            AV::AV_CODEC_ID_WMV1 => Id::WMV1,
            AV::AV_CODEC_ID_WMV2 => Id::WMV2,
            AV::AV_CODEC_ID_H263P => Id::H263P,
            AV::AV_CODEC_ID_H263I => Id::H263I,
            AV::AV_CODEC_ID_FLV1 => Id::FLV1,
            AV::AV_CODEC_ID_SVQ1 => Id::SVQ1,
            AV::AV_CODEC_ID_SVQ3 => Id::SVQ3,
            AV::AV_CODEC_ID_DVVIDEO => Id::DVVIDEO,
            AV::AV_CODEC_ID_HUFFYUV => Id::HUFFYUV,
            AV::AV_CODEC_ID_CYUV => Id::CYUV,
            AV::AV_CODEC_ID_H264 => Id::H264,
            AV::AV_CODEC_ID_INDEO3 => Id::INDEO3,
            AV::AV_CODEC_ID_VP3 => Id::VP3,
            AV::AV_CODEC_ID_THEORA => Id::THEORA,
            AV::AV_CODEC_ID_ASV1 => Id::ASV1,
            AV::AV_CODEC_ID_ASV2 => Id::ASV2,
            AV::AV_CODEC_ID_FFV1 => Id::FFV1,
            AV::AV_CODEC_ID_4XM => Id::XM4,
            AV::AV_CODEC_ID_VCR1 => Id::VCR1,
            AV::AV_CODEC_ID_CLJR => Id::CLJR,
            AV::AV_CODEC_ID_MDEC => Id::MDEC,
            AV::AV_CODEC_ID_ROQ => Id::ROQ,
            AV::AV_CODEC_ID_INTERPLAY_VIDEO => Id::INTERPLAY_VIDEO,
            AV::AV_CODEC_ID_XAN_WC3 => Id::XAN_WC3,
            AV::AV_CODEC_ID_XAN_WC4 => Id::XAN_WC4,
            AV::AV_CODEC_ID_RPZA => Id::RPZA,
            AV::AV_CODEC_ID_CINEPAK => Id::CINEPAK,
            AV::AV_CODEC_ID_WS_VQA => Id::WS_VQA,
            AV::AV_CODEC_ID_MSRLE => Id::MSRLE,
            AV::AV_CODEC_ID_MSVIDEO1 => Id::MSVIDEO1,
            AV::AV_CODEC_ID_IDCIN => Id::IDCIN,
            AV::AV_CODEC_ID_8BPS => Id::BPS8,
            AV::AV_CODEC_ID_SMC => Id::SMC,
            AV::AV_CODEC_ID_FLIC => Id::FLIC,
            AV::AV_CODEC_ID_TRUEMOTION1 => Id::TRUEMOTION1,
            AV::AV_CODEC_ID_VMDVIDEO => Id::VMDVIDEO,
            AV::AV_CODEC_ID_MSZH => Id::MSZH,
            AV::AV_CODEC_ID_ZLIB => Id::ZLIB,
            AV::AV_CODEC_ID_QTRLE => Id::QTRLE,
            AV::AV_CODEC_ID_TSCC => Id::TSCC,
            AV::AV_CODEC_ID_ULTI => Id::ULTI,
            AV::AV_CODEC_ID_QDRAW => Id::QDRAW,
            AV::AV_CODEC_ID_VIXL => Id::VIXL,
            AV::AV_CODEC_ID_QPEG => Id::QPEG,
            AV::AV_CODEC_ID_PNG => Id::PNG,
            AV::AV_CODEC_ID_PPM => Id::PPM,
            AV::AV_CODEC_ID_PBM => Id::PBM,
            AV::AV_CODEC_ID_PGM => Id::PGM,
            AV::AV_CODEC_ID_PGMYUV => Id::PGMYUV,
            AV::AV_CODEC_ID_PAM => Id::PAM,
            AV::AV_CODEC_ID_FFVHUFF => Id::FFVHUFF,
            AV::AV_CODEC_ID_RV30 => Id::RV30,
            AV::AV_CODEC_ID_RV40 => Id::RV40,
            AV::AV_CODEC_ID_VC1 => Id::VC1,
            AV::AV_CODEC_ID_WMV3 => Id::WMV3,
            AV::AV_CODEC_ID_LOCO => Id::LOCO,
            AV::AV_CODEC_ID_WNV1 => Id::WNV1,
            AV::AV_CODEC_ID_AASC => Id::AASC,
            AV::AV_CODEC_ID_INDEO2 => Id::INDEO2,
            AV::AV_CODEC_ID_FRAPS => Id::FRAPS,
            AV::AV_CODEC_ID_TRUEMOTION2 => Id::TRUEMOTION2,
            AV::AV_CODEC_ID_BMP => Id::BMP,
            AV::AV_CODEC_ID_CSCD => Id::CSCD,
            AV::AV_CODEC_ID_MMVIDEO => Id::MMVIDEO,
            AV::AV_CODEC_ID_ZMBV => Id::ZMBV,
            AV::AV_CODEC_ID_AVS => Id::AVS,
            AV::AV_CODEC_ID_SMACKVIDEO => Id::SMACKVIDEO,
            AV::AV_CODEC_ID_NUV => Id::NUV,
            AV::AV_CODEC_ID_KMVC => Id::KMVC,
            AV::AV_CODEC_ID_FLASHSV => Id::FLASHSV,
            AV::AV_CODEC_ID_CAVS => Id::CAVS,
            AV::AV_CODEC_ID_JPEG2000 => Id::JPEG2000,
            AV::AV_CODEC_ID_VMNC => Id::VMNC,
            AV::AV_CODEC_ID_VP5 => Id::VP5,
            AV::AV_CODEC_ID_VP6 => Id::VP6,
            AV::AV_CODEC_ID_VP6F => Id::VP6F,
            AV::AV_CODEC_ID_TARGA => Id::TARGA,
            AV::AV_CODEC_ID_DSICINVIDEO => Id::DSICINVIDEO,
            AV::AV_CODEC_ID_TIERTEXSEQVIDEO => Id::TIERTEXSEQVIDEO,
            AV::AV_CODEC_ID_TIFF => Id::TIFF,
            AV::AV_CODEC_ID_GIF => Id::GIF,
            AV::AV_CODEC_ID_DXA => Id::DXA,
            AV::AV_CODEC_ID_DNXHD => Id::DNXHD,
            AV::AV_CODEC_ID_THP => Id::THP,
            AV::AV_CODEC_ID_SGI => Id::SGI,
            AV::AV_CODEC_ID_C93 => Id::C93,
            AV::AV_CODEC_ID_BETHSOFTVID => Id::BETHSOFTVID,
            AV::AV_CODEC_ID_PTX => Id::PTX,
            AV::AV_CODEC_ID_TXD => Id::TXD,
            AV::AV_CODEC_ID_VP6A => Id::VP6A,
            AV::AV_CODEC_ID_AMV => Id::AMV,
            AV::AV_CODEC_ID_VB => Id::VB,
            AV::AV_CODEC_ID_PCX => Id::PCX,
            AV::AV_CODEC_ID_SUNRAST => Id::SUNRAST,
            AV::AV_CODEC_ID_INDEO4 => Id::INDEO4,
            AV::AV_CODEC_ID_INDEO5 => Id::INDEO5,
            AV::AV_CODEC_ID_MIMIC => Id::MIMIC,
            AV::AV_CODEC_ID_RL2 => Id::RL2,
            AV::AV_CODEC_ID_ESCAPE124 => Id::ESCAPE124,
            AV::AV_CODEC_ID_DIRAC => Id::DIRAC,
            AV::AV_CODEC_ID_BFI => Id::BFI,
            AV::AV_CODEC_ID_CMV => Id::CMV,
            AV::AV_CODEC_ID_MOTIONPIXELS => Id::MOTIONPIXELS,
            AV::AV_CODEC_ID_TGV => Id::TGV,
            AV::AV_CODEC_ID_TGQ => Id::TGQ,
            AV::AV_CODEC_ID_TQI => Id::TQI,
            AV::AV_CODEC_ID_AURA => Id::AURA,
            AV::AV_CODEC_ID_AURA2 => Id::AURA2,
            AV::AV_CODEC_ID_V210X => Id::V210X,
            AV::AV_CODEC_ID_TMV => Id::TMV,
            AV::AV_CODEC_ID_V210 => Id::V210,
            AV::AV_CODEC_ID_DPX => Id::DPX,
            AV::AV_CODEC_ID_MAD => Id::MAD,
            AV::AV_CODEC_ID_FRWU => Id::FRWU,
            AV::AV_CODEC_ID_FLASHSV2 => Id::FLASHSV2,
            AV::AV_CODEC_ID_CDGRAPHICS => Id::CDGRAPHICS,
            AV::AV_CODEC_ID_R210 => Id::R210,
            AV::AV_CODEC_ID_ANM => Id::ANM,
            AV::AV_CODEC_ID_BINKVIDEO => Id::BINKVIDEO,
            AV::AV_CODEC_ID_IFF_ILBM => Id::IFF_ILBM,
            AV::AV_CODEC_ID_KGV1 => Id::KGV1,
            AV::AV_CODEC_ID_YOP => Id::YOP,
            AV::AV_CODEC_ID_VP8 => Id::VP8,
            AV::AV_CODEC_ID_PICTOR => Id::PICTOR,
            AV::AV_CODEC_ID_ANSI => Id::ANSI,
            AV::AV_CODEC_ID_A64_MULTI => Id::A64_MULTI,
            AV::AV_CODEC_ID_A64_MULTI5 => Id::A64_MULTI5,
            AV::AV_CODEC_ID_R10K => Id::R10K,
            AV::AV_CODEC_ID_MXPEG => Id::MXPEG,
            AV::AV_CODEC_ID_LAGARITH => Id::LAGARITH,
            AV::AV_CODEC_ID_PRORES => Id::PRORES,
            AV::AV_CODEC_ID_JV => Id::JV,
            AV::AV_CODEC_ID_DFA => Id::DFA,
            AV::AV_CODEC_ID_WMV3IMAGE => Id::WMV3IMAGE,
            AV::AV_CODEC_ID_VC1IMAGE => Id::VC1IMAGE,
            AV::AV_CODEC_ID_UTVIDEO => Id::UTVIDEO,
            AV::AV_CODEC_ID_BMV_VIDEO => Id::BMV_VIDEO,
            AV::AV_CODEC_ID_VBLE => Id::VBLE,
            AV::AV_CODEC_ID_DXTORY => Id::DXTORY,
            AV::AV_CODEC_ID_V410 => Id::V410,
            AV::AV_CODEC_ID_XWD => Id::XWD,
            AV::AV_CODEC_ID_CDXL => Id::CDXL,
            AV::AV_CODEC_ID_XBM => Id::XBM,
            AV::AV_CODEC_ID_ZEROCODEC => Id::ZEROCODEC,
            AV::AV_CODEC_ID_MSS1 => Id::MSS1,
            AV::AV_CODEC_ID_MSA1 => Id::MSA1,
            AV::AV_CODEC_ID_TSCC2 => Id::TSCC2,
            AV::AV_CODEC_ID_MTS2 => Id::MTS2,
            AV::AV_CODEC_ID_CLLC => Id::CLLC,
            AV::AV_CODEC_ID_MSS2 => Id::MSS2,
            AV::AV_CODEC_ID_VP9 => Id::VP9,
            AV::AV_CODEC_ID_AIC => Id::AIC,
            AV::AV_CODEC_ID_ESCAPE130 => Id::ESCAPE130,
            AV::AV_CODEC_ID_G2M => Id::G2M,
            AV::AV_CODEC_ID_WEBP => Id::WEBP,
            AV::AV_CODEC_ID_HNM4_VIDEO => Id::HNM4_VIDEO,
            AV::AV_CODEC_ID_HEVC => Id::HEVC,
            AV::AV_CODEC_ID_FIC => Id::FIC,
            AV::AV_CODEC_ID_ALIAS_PIX => Id::ALIAS_PIX,
            AV::AV_CODEC_ID_BRENDER_PIX => Id::BRENDER_PIX,
            AV::AV_CODEC_ID_PAF_VIDEO => Id::PAF_VIDEO,
            AV::AV_CODEC_ID_EXR => Id::EXR,
            AV::AV_CODEC_ID_VP7 => Id::VP7,
            AV::AV_CODEC_ID_SANM => Id::SANM,
            AV::AV_CODEC_ID_SGIRLE => Id::SGIRLE,
            AV::AV_CODEC_ID_MVC1 => Id::MVC1,
            AV::AV_CODEC_ID_MVC2 => Id::MVC2,
            AV::AV_CODEC_ID_HQX => Id::HQX,
            AV::AV_CODEC_ID_TDSC => Id::TDSC,
            AV::AV_CODEC_ID_HQ_HQA => Id::HQ_HQA,
            AV::AV_CODEC_ID_HAP => Id::HAP,
            AV::AV_CODEC_ID_DDS => Id::DDS,
            AV::AV_CODEC_ID_DXV => Id::DXV,
            AV::AV_CODEC_ID_SCREENPRESSO => Id::SCREENPRESSO,
            AV::AV_CODEC_ID_RSCC => Id::RSCC,

            AV::AV_CODEC_ID_Y41P => Id::Y41P,
            AV::AV_CODEC_ID_AVRP => Id::AVRP,
            AV::AV_CODEC_ID_012V => Id::V012,
            AV::AV_CODEC_ID_AVUI => Id::AVUI,
            #[cfg(not(feature = "ffmpeg_7_0"))]
            AV::AV_CODEC_ID_AYUV => Id::AYUV,
            AV::AV_CODEC_ID_TARGA_Y216 => Id::TARGA_Y216,
            AV::AV_CODEC_ID_V308 => Id::V308,
            AV::AV_CODEC_ID_V408 => Id::V408,
            AV::AV_CODEC_ID_YUV4 => Id::YUV4,
            AV::AV_CODEC_ID_AVRN => Id::AVRN,
            AV::AV_CODEC_ID_CPIA => Id::CPIA,
            AV::AV_CODEC_ID_XFACE => Id::XFACE,
            AV::AV_CODEC_ID_SNOW => Id::SNOW,
            AV::AV_CODEC_ID_SMVJPEG => Id::SMVJPEG,
            AV::AV_CODEC_ID_APNG => Id::APNG,
            AV::AV_CODEC_ID_DAALA => Id::DAALA,
            AV::AV_CODEC_ID_CFHD => Id::CFHD,
            AV::AV_CODEC_ID_TRUEMOTION2RT => Id::TRUEMOTION2RT,
            AV::AV_CODEC_ID_M101 => Id::M101,
            AV::AV_CODEC_ID_MAGICYUV => Id::MAGICYUV,
            AV::AV_CODEC_ID_SHEERVIDEO => Id::SHEERVIDEO,
            AV::AV_CODEC_ID_YLC => Id::YLC,

            /* various PCM "codecs" */
            AV::AV_CODEC_ID_PCM_S16LE => Id::PCM_S16LE,
            AV::AV_CODEC_ID_PCM_S16BE => Id::PCM_S16BE,
            AV::AV_CODEC_ID_PCM_U16LE => Id::PCM_U16LE,
            AV::AV_CODEC_ID_PCM_U16BE => Id::PCM_U16BE,
            AV::AV_CODEC_ID_PCM_S8 => Id::PCM_S8,
            AV::AV_CODEC_ID_PCM_U8 => Id::PCM_U8,
            AV::AV_CODEC_ID_PCM_MULAW => Id::PCM_MULAW,
            AV::AV_CODEC_ID_PCM_ALAW => Id::PCM_ALAW,
            AV::AV_CODEC_ID_PCM_S32LE => Id::PCM_S32LE,
            AV::AV_CODEC_ID_PCM_S32BE => Id::PCM_S32BE,
            AV::AV_CODEC_ID_PCM_U32LE => Id::PCM_U32LE,
            AV::AV_CODEC_ID_PCM_U32BE => Id::PCM_U32BE,
            AV::AV_CODEC_ID_PCM_S24LE => Id::PCM_S24LE,
            AV::AV_CODEC_ID_PCM_S24BE => Id::PCM_S24BE,
            AV::AV_CODEC_ID_PCM_U24LE => Id::PCM_U24LE,
            AV::AV_CODEC_ID_PCM_U24BE => Id::PCM_U24BE,
            AV::AV_CODEC_ID_PCM_S24DAUD => Id::PCM_S24DAUD,
            AV::AV_CODEC_ID_PCM_ZORK => Id::PCM_ZORK,
            AV::AV_CODEC_ID_PCM_S16LE_PLANAR => Id::PCM_S16LE_PLANAR,
            AV::AV_CODEC_ID_PCM_DVD => Id::PCM_DVD,
            AV::AV_CODEC_ID_PCM_F32BE => Id::PCM_F32BE,
            AV::AV_CODEC_ID_PCM_F32LE => Id::PCM_F32LE,
            AV::AV_CODEC_ID_PCM_F64BE => Id::PCM_F64BE,
            AV::AV_CODEC_ID_PCM_F64LE => Id::PCM_F64LE,
            AV::AV_CODEC_ID_PCM_BLURAY => Id::PCM_BLURAY,
            AV::AV_CODEC_ID_PCM_LXF => Id::PCM_LXF,
            AV::AV_CODEC_ID_S302M => Id::S302M,
            AV::AV_CODEC_ID_PCM_S8_PLANAR => Id::PCM_S8_PLANAR,
            AV::AV_CODEC_ID_PCM_S24LE_PLANAR => Id::PCM_S24LE_PLANAR,
            AV::AV_CODEC_ID_PCM_S32LE_PLANAR => Id::PCM_S32LE_PLANAR,
            AV::AV_CODEC_ID_PCM_S16BE_PLANAR => Id::PCM_S16BE_PLANAR,

            AV::AV_CODEC_ID_PCM_S64LE => Id::PCM_S64LE,
            AV::AV_CODEC_ID_PCM_S64BE => Id::PCM_S64BE,

            /* various ADPCM codecs */
            AV::AV_CODEC_ID_ADPCM_IMA_QT => Id::ADPCM_IMA_QT,
            AV::AV_CODEC_ID_ADPCM_IMA_WAV => Id::ADPCM_IMA_WAV,
            AV::AV_CODEC_ID_ADPCM_IMA_DK3 => Id::ADPCM_IMA_DK3,
            AV::AV_CODEC_ID_ADPCM_IMA_DK4 => Id::ADPCM_IMA_DK4,
            AV::AV_CODEC_ID_ADPCM_IMA_WS => Id::ADPCM_IMA_WS,
            AV::AV_CODEC_ID_ADPCM_IMA_SMJPEG => Id::ADPCM_IMA_SMJPEG,
            AV::AV_CODEC_ID_ADPCM_MS => Id::ADPCM_MS,
            AV::AV_CODEC_ID_ADPCM_4XM => Id::ADPCM_4XM,
            AV::AV_CODEC_ID_ADPCM_XA => Id::ADPCM_XA,
            AV::AV_CODEC_ID_ADPCM_ADX => Id::ADPCM_ADX,
            AV::AV_CODEC_ID_ADPCM_EA => Id::ADPCM_EA,
            AV::AV_CODEC_ID_ADPCM_G726 => Id::ADPCM_G726,
            AV::AV_CODEC_ID_ADPCM_CT => Id::ADPCM_CT,
            AV::AV_CODEC_ID_ADPCM_SWF => Id::ADPCM_SWF,
            AV::AV_CODEC_ID_ADPCM_YAMAHA => Id::ADPCM_YAMAHA,
            AV::AV_CODEC_ID_ADPCM_SBPRO_4 => Id::ADPCM_SBPRO_4,
            AV::AV_CODEC_ID_ADPCM_SBPRO_3 => Id::ADPCM_SBPRO_3,
            AV::AV_CODEC_ID_ADPCM_SBPRO_2 => Id::ADPCM_SBPRO_2,
            AV::AV_CODEC_ID_ADPCM_THP => Id::ADPCM_THP,
            AV::AV_CODEC_ID_ADPCM_IMA_AMV => Id::ADPCM_IMA_AMV,
            AV::AV_CODEC_ID_ADPCM_EA_R1 => Id::ADPCM_EA_R1,
            AV::AV_CODEC_ID_ADPCM_EA_R3 => Id::ADPCM_EA_R3,
            AV::AV_CODEC_ID_ADPCM_EA_R2 => Id::ADPCM_EA_R2,
            AV::AV_CODEC_ID_ADPCM_IMA_EA_SEAD => Id::ADPCM_IMA_EA_SEAD,
            AV::AV_CODEC_ID_ADPCM_IMA_EA_EACS => Id::ADPCM_IMA_EA_EACS,
            AV::AV_CODEC_ID_ADPCM_EA_XAS => Id::ADPCM_EA_XAS,
            AV::AV_CODEC_ID_ADPCM_EA_MAXIS_XA => Id::ADPCM_EA_MAXIS_XA,
            AV::AV_CODEC_ID_ADPCM_IMA_ISS => Id::ADPCM_IMA_ISS,
            AV::AV_CODEC_ID_ADPCM_G722 => Id::ADPCM_G722,
            AV::AV_CODEC_ID_ADPCM_IMA_APC => Id::ADPCM_IMA_APC,
            AV::AV_CODEC_ID_ADPCM_VIMA => Id::ADPCM_VIMA,

            AV::AV_CODEC_ID_ADPCM_AFC => Id::ADPCM_AFC,
            AV::AV_CODEC_ID_ADPCM_IMA_OKI => Id::ADPCM_IMA_OKI,
            AV::AV_CODEC_ID_ADPCM_DTK => Id::ADPCM_DTK,
            AV::AV_CODEC_ID_ADPCM_IMA_RAD => Id::ADPCM_IMA_RAD,
            AV::AV_CODEC_ID_ADPCM_G726LE => Id::ADPCM_G726LE,
            AV::AV_CODEC_ID_ADPCM_THP_LE => Id::ADPCM_THP_LE,
            AV::AV_CODEC_ID_ADPCM_PSX => Id::ADPCM_PSX,
            AV::AV_CODEC_ID_ADPCM_AICA => Id::ADPCM_AICA,
            AV::AV_CODEC_ID_ADPCM_IMA_DAT4 => Id::ADPCM_IMA_DAT4,
            AV::AV_CODEC_ID_ADPCM_MTAF => Id::ADPCM_MTAF,

            /* AMR */
            AV::AV_CODEC_ID_AMR_NB => Id::AMR_NB,
            AV::AV_CODEC_ID_AMR_WB => Id::AMR_WB,

            /* RealAudio codecs*/
            AV::AV_CODEC_ID_RA_144 => Id::RA_144,
            AV::AV_CODEC_ID_RA_288 => Id::RA_288,

            /* various DPCM codecs */
            AV::AV_CODEC_ID_ROQ_DPCM => Id::ROQ_DPCM,
            AV::AV_CODEC_ID_INTERPLAY_DPCM => Id::INTERPLAY_DPCM,
            AV::AV_CODEC_ID_XAN_DPCM => Id::XAN_DPCM,
            AV::AV_CODEC_ID_SOL_DPCM => Id::SOL_DPCM,

            AV::AV_CODEC_ID_SDX2_DPCM => Id::SDX2_DPCM,

            /* audio codecs */
            AV::AV_CODEC_ID_MP2 => Id::MP2,
            AV::AV_CODEC_ID_MP3 => Id::MP3,
            AV::AV_CODEC_ID_AAC => Id::AAC,
            AV::AV_CODEC_ID_AC3 => Id::AC3,
            AV::AV_CODEC_ID_DTS => Id::DTS,
            AV::AV_CODEC_ID_VORBIS => Id::VORBIS,
            AV::AV_CODEC_ID_DVAUDIO => Id::DVAUDIO,
            AV::AV_CODEC_ID_WMAV1 => Id::WMAV1,
            AV::AV_CODEC_ID_WMAV2 => Id::WMAV2,
            AV::AV_CODEC_ID_MACE3 => Id::MACE3,
            AV::AV_CODEC_ID_MACE6 => Id::MACE6,
            AV::AV_CODEC_ID_VMDAUDIO => Id::VMDAUDIO,
            AV::AV_CODEC_ID_FLAC => Id::FLAC,
            AV::AV_CODEC_ID_MP3ADU => Id::MP3ADU,
            AV::AV_CODEC_ID_MP3ON4 => Id::MP3ON4,
            AV::AV_CODEC_ID_SHORTEN => Id::SHORTEN,
            AV::AV_CODEC_ID_ALAC => Id::ALAC,
            AV::AV_CODEC_ID_WESTWOOD_SND1 => Id::WESTWOOD_SND1,
            AV::AV_CODEC_ID_GSM => Id::GSM,
            AV::AV_CODEC_ID_QDM2 => Id::QDM2,
            AV::AV_CODEC_ID_COOK => Id::COOK,
            AV::AV_CODEC_ID_TRUESPEECH => Id::TRUESPEECH,
            AV::AV_CODEC_ID_TTA => Id::TTA,
            AV::AV_CODEC_ID_SMACKAUDIO => Id::SMACKAUDIO,
            AV::AV_CODEC_ID_QCELP => Id::QCELP,
            AV::AV_CODEC_ID_WAVPACK => Id::WAVPACK,
            AV::AV_CODEC_ID_DSICINAUDIO => Id::DSICINAUDIO,
            AV::AV_CODEC_ID_IMC => Id::IMC,
            AV::AV_CODEC_ID_MUSEPACK7 => Id::MUSEPACK7,
            AV::AV_CODEC_ID_MLP => Id::MLP,
            AV::AV_CODEC_ID_GSM_MS => Id::GSM_MS,
            AV::AV_CODEC_ID_ATRAC3 => Id::ATRAC3,
            AV::AV_CODEC_ID_APE => Id::APE,
            AV::AV_CODEC_ID_NELLYMOSER => Id::NELLYMOSER,
            AV::AV_CODEC_ID_MUSEPACK8 => Id::MUSEPACK8,
            AV::AV_CODEC_ID_SPEEX => Id::SPEEX,
            AV::AV_CODEC_ID_WMAVOICE => Id::WMAVOICE,
            AV::AV_CODEC_ID_WMAPRO => Id::WMAPRO,
            AV::AV_CODEC_ID_WMALOSSLESS => Id::WMALOSSLESS,
            AV::AV_CODEC_ID_ATRAC3P => Id::ATRAC3P,
            AV::AV_CODEC_ID_EAC3 => Id::EAC3,
            AV::AV_CODEC_ID_SIPR => Id::SIPR,
            AV::AV_CODEC_ID_MP1 => Id::MP1,
            AV::AV_CODEC_ID_TWINVQ => Id::TWINVQ,
            AV::AV_CODEC_ID_TRUEHD => Id::TRUEHD,
            AV::AV_CODEC_ID_MP4ALS => Id::MP4ALS,
            AV::AV_CODEC_ID_ATRAC1 => Id::ATRAC1,
            AV::AV_CODEC_ID_BINKAUDIO_RDFT => Id::BINKAUDIO_RDFT,
            AV::AV_CODEC_ID_BINKAUDIO_DCT => Id::BINKAUDIO_DCT,
            AV::AV_CODEC_ID_AAC_LATM => Id::AAC_LATM,
            AV::AV_CODEC_ID_QDMC => Id::QDMC,
            AV::AV_CODEC_ID_CELT => Id::CELT,
            AV::AV_CODEC_ID_G723_1 => Id::G723_1,
            AV::AV_CODEC_ID_G729 => Id::G729,
            AV::AV_CODEC_ID_8SVX_EXP => Id::SVX_EXP8,
            AV::AV_CODEC_ID_8SVX_FIB => Id::SVX_FIB8,
            AV::AV_CODEC_ID_BMV_AUDIO => Id::BMV_AUDIO,
            AV::AV_CODEC_ID_RALF => Id::RALF,
            AV::AV_CODEC_ID_IAC => Id::IAC,
            AV::AV_CODEC_ID_ILBC => Id::ILBC,
            AV::AV_CODEC_ID_OPUS => Id::OPUS,
            AV::AV_CODEC_ID_COMFORT_NOISE => Id::COMFORT_NOISE,
            AV::AV_CODEC_ID_TAK => Id::TAK,
            AV::AV_CODEC_ID_METASOUND => Id::METASOUND,
            AV::AV_CODEC_ID_PAF_AUDIO => Id::PAF_AUDIO,
            AV::AV_CODEC_ID_ON2AVC => Id::ON2AVC,
            AV::AV_CODEC_ID_DSS_SP => Id::DSS_SP,

            AV::AV_CODEC_ID_CODEC2 => Id::CODEC2,
            AV::AV_CODEC_ID_FFWAVESYNTH => Id::FFWAVESYNTH,
            AV::AV_CODEC_ID_SONIC => Id::SONIC,
            AV::AV_CODEC_ID_SONIC_LS => Id::SONIC_LS,
            AV::AV_CODEC_ID_EVRC => Id::EVRC,
            AV::AV_CODEC_ID_SMV => Id::SMV,
            AV::AV_CODEC_ID_DSD_LSBF => Id::DSD_LSBF,
            AV::AV_CODEC_ID_DSD_MSBF => Id::DSD_MSBF,
            AV::AV_CODEC_ID_DSD_LSBF_PLANAR => Id::DSD_LSBF_PLANAR,
            AV::AV_CODEC_ID_DSD_MSBF_PLANAR => Id::DSD_MSBF_PLANAR,
            AV::AV_CODEC_ID_4GV => Id::_4GV,
            AV::AV_CODEC_ID_INTERPLAY_ACM => Id::INTERPLAY_ACM,
            AV::AV_CODEC_ID_XMA1 => Id::XMA1,
            AV::AV_CODEC_ID_XMA2 => Id::XMA2,
            AV::AV_CODEC_ID_DST => Id::DST,

            /* subtitle codecs */
            AV::AV_CODEC_ID_DVD_SUBTITLE => Id::DVD_SUBTITLE,
            AV::AV_CODEC_ID_DVB_SUBTITLE => Id::DVB_SUBTITLE,
            AV::AV_CODEC_ID_TEXT => Id::TEXT,
            AV::AV_CODEC_ID_XSUB => Id::XSUB,
            AV::AV_CODEC_ID_SSA => Id::SSA,
            AV::AV_CODEC_ID_MOV_TEXT => Id::MOV_TEXT,
            AV::AV_CODEC_ID_HDMV_PGS_SUBTITLE => Id::HDMV_PGS_SUBTITLE,
            AV::AV_CODEC_ID_DVB_TELETEXT => Id::DVB_TELETEXT,
            AV::AV_CODEC_ID_SRT => Id::SRT,

            AV::AV_CODEC_ID_MICRODVD => Id::MICRODVD,
            AV::AV_CODEC_ID_EIA_608 => Id::EIA_608,
            AV::AV_CODEC_ID_JACOSUB => Id::JACOSUB,
            AV::AV_CODEC_ID_SAMI => Id::SAMI,
            AV::AV_CODEC_ID_REALTEXT => Id::REALTEXT,
            AV::AV_CODEC_ID_STL => Id::STL,
            AV::AV_CODEC_ID_SUBVIEWER1 => Id::SUBVIEWER1,
            AV::AV_CODEC_ID_SUBVIEWER => Id::SUBVIEWER,
            AV::AV_CODEC_ID_SUBRIP => Id::SUBRIP,
            AV::AV_CODEC_ID_WEBVTT => Id::WEBVTT,
            AV::AV_CODEC_ID_MPL2 => Id::MPL2,
            AV::AV_CODEC_ID_VPLAYER => Id::VPLAYER,
            AV::AV_CODEC_ID_PJS => Id::PJS,
            AV::AV_CODEC_ID_ASS => Id::ASS,
            AV::AV_CODEC_ID_HDMV_TEXT_SUBTITLE => Id::HDMV_TEXT_SUBTITLE,

            /* other specific kind of codecs (generally used for attachments) */
            AV::AV_CODEC_ID_TTF => Id::TTF,

            AV::AV_CODEC_ID_SCTE_35 => Id::SCTE_35,
            AV::AV_CODEC_ID_BINTEXT => Id::BINTEXT,
            AV::AV_CODEC_ID_XBIN => Id::XBIN,
            AV::AV_CODEC_ID_IDF => Id::IDF,
            AV::AV_CODEC_ID_OTF => Id::OTF,
            AV::AV_CODEC_ID_SMPTE_KLV => Id::SMPTE_KLV,
            AV::AV_CODEC_ID_DVD_NAV => Id::DVD_NAV,
            AV::AV_CODEC_ID_TIMED_ID3 => Id::TIMED_ID3,
            AV::AV_CODEC_ID_BIN_DATA => Id::BIN_DATA,

            AV::AV_CODEC_ID_PROBE => Id::PROBE,

            AV::AV_CODEC_ID_MPEG2TS => Id::MPEG2TS,
            AV::AV_CODEC_ID_MPEG4SYSTEMS => Id::MPEG4SYSTEMS,
            AV::AV_CODEC_ID_FFMETADATA => Id::FFMETADATA,
            AV::AV_CODEC_ID_WRAPPED_AVFRAME => Id::WRAPPED_AVFRAME,
            AV::AV_CODEC_ID_PSD => Id::PSD,
            AV::AV_CODEC_ID_PIXLET => Id::PIXLET,
            AV::AV_CODEC_ID_SPEEDHQ => Id::SPEEDHQ,
            AV::AV_CODEC_ID_CLEARVIDEO => Id::CLEARVIDEO,
            AV::AV_CODEC_ID_FMVC => Id::FMVC,
            AV::AV_CODEC_ID_SCPR => Id::SCPR,
            AV::AV_CODEC_ID_XPM => Id::XPM,
            AV::AV_CODEC_ID_AV1 => Id::AV1,
            AV::AV_CODEC_ID_PCM_F16LE => Id::PCM_F16LE,
            AV::AV_CODEC_ID_PCM_F24LE => Id::PCM_F24LE,
            AV::AV_CODEC_ID_ATRAC3AL => Id::ATRAC3AL,
            AV::AV_CODEC_ID_ATRAC3PAL => Id::ATRAC3PAL,

            AV::AV_CODEC_ID_BITPACKED => Id::BITPACKED,
            AV::AV_CODEC_ID_MSCC => Id::MSCC,
            AV::AV_CODEC_ID_SRGC => Id::SRGC,
            AV::AV_CODEC_ID_SVG => Id::SVG,
            AV::AV_CODEC_ID_GDV => Id::GDV,
            AV::AV_CODEC_ID_FITS => Id::FITS,
            AV::AV_CODEC_ID_GREMLIN_DPCM => Id::GREMLIN_DPCM,
            AV::AV_CODEC_ID_DOLBY_E => Id::DOLBY_E,

            AV::AV_CODEC_ID_APTX => Id::APTX,
            AV::AV_CODEC_ID_APTX_HD => Id::APTX_HD,
            AV::AV_CODEC_ID_SBC => Id::SBC,

            AV::AV_CODEC_ID_AVS2 => Id::AVS2,
            AV::AV_CODEC_ID_IMM4 => Id::IMM4,
            AV::AV_CODEC_ID_PROSUMER => Id::PROSUMER,
            AV::AV_CODEC_ID_MWSC => Id::MWSC,
            AV::AV_CODEC_ID_WCMV => Id::WCMV,
            AV::AV_CODEC_ID_RASC => Id::RASC,
            AV::AV_CODEC_ID_PCM_VIDC => Id::PCM_VIDC,
            AV::AV_CODEC_ID_ATRAC9 => Id::ATRAC9,
            AV::AV_CODEC_ID_TTML => Id::TTML,

            AV::AV_CODEC_ID_HYMT => Id::HYMT,
            AV::AV_CODEC_ID_ARBC => Id::ARBC,
            AV::AV_CODEC_ID_AGM => Id::AGM,
            AV::AV_CODEC_ID_LSCR => Id::LSCR,
            AV::AV_CODEC_ID_VP4 => Id::VP4,
            AV::AV_CODEC_ID_ADPCM_AGM => Id::ADPCM_AGM,
            AV::AV_CODEC_ID_HCOM => Id::HCOM,
            AV::AV_CODEC_ID_ARIB_CAPTION => Id::ARIB_CAPTION,

            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_IMM5 => Id::IMM5,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_MVDV => Id::MVDV,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_MVHA => Id::MVHA,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_CDTOONS => Id::CDTOONS,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_MV30 => Id::MV30,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_NOTCHLC => Id::NOTCHLC,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_PFM => Id::PFM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_ARGO => Id::ADPCM_ARGO,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_IMA_SSI => Id::ADPCM_IMA_SSI,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_ZORK => Id::ADPCM_ZORK,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_IMA_APM => Id::ADPCM_IMA_APM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_IMA_ALP => Id::ADPCM_IMA_ALP,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_IMA_MTF => Id::ADPCM_IMA_MTF,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ADPCM_IMA_CUNNING => Id::ADPCM_IMA_CUNNING,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_DERF_DPCM => Id::DERF_DPCM,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_ACELP_KELVIN => Id::ACELP_KELVIN,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_MPEGH_3D_AUDIO => Id::MPEGH_3D_AUDIO,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_SIREN => Id::SIREN,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_HCA => Id::HCA,
            #[cfg(feature = "ffmpeg_4_3")]
            AV::AV_CODEC_ID_EPG => Id::EPG,

            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_PGX => Id::PGX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_AVS3 => Id::AVS3,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_MSP2 => Id::MSP2,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_VVC => Id::VVC,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_MOBICLIP => Id::MOBICLIP,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_PHOTOCD => Id::PHOTOCD,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_IPU => Id::IPU,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_ARGO => Id::ARGO,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_CRI => Id::CRI,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_SIMBIOSIS_IMX => Id::SIMBIOSIS_IMX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_SGA_VIDEO => Id::SGA_VIDEO,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_PCM_SGA => Id::PCM_SGA,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_ADPCM_IMA_MOFLEX => Id::ADPCM_IMA_MOFLEX,
            #[cfg(feature = "ffmpeg_4_4")]
            AV::AV_CODEC_ID_FASTAUDIO => Id::FASTAUDIO,

            #[cfg(feature = "ffmpeg_5_0")]
            AV::AV_CODEC_ID_GEM => Id::GEM,
            #[cfg(feature = "ffmpeg_5_0")]
            AV::AV_CODEC_ID_ADPCM_IMA_ACORN => Id::ADPCM_IMA_ACORN,
            #[cfg(feature = "ffmpeg_5_0")]
            AV::AV_CODEC_ID_MSNSIREN => Id::MSNSIREN,

            #[cfg(feature = "ffmpeg_5_1")]
            AV::AV_CODEC_ID_VBN => Id::VBN,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::AV_CODEC_ID_JPEGXL => Id::JPEGXL,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::AV_CODEC_ID_QOI => Id::QOI,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::AV_CODEC_ID_PHM => Id::PHM,
            #[cfg(feature = "ffmpeg_5_1")]
            AV::AV_CODEC_ID_DFPWM => Id::DFPWM,

            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_RADIANCE_HDR => Id::RADIANCE_HDR,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_WBMP => Id::WBMP,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_MEDIA100 => Id::MEDIA100,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_VQC => Id::VQC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_ADPCM_XMD => Id::ADPCM_XMD,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_WADY_DPCM => Id::WADY_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_CBD2_DPCM => Id::CBD2_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_BONK => Id::BONK,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_MISC4 => Id::MISC4,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_APAC => Id::APAC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_FTR => Id::FTR,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_WAVARC => Id::WAVARC,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_RKA => Id::RKA,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_VNULL => Id::VNULL,
            #[cfg(feature = "ffmpeg_6_0")]
            AV::AV_CODEC_ID_ANULL => Id::ANULL,

            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_PDV => Id::PDV,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_EVC => Id::EVC,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_RTV1 => Id::RTV1,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_VMIX => Id::VMIX,
            #[cfg(feature = "ffmpeg_7_0")]
            AV::AV_CODEC_ID_LEAD => Id::LEAD,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_AC4 => Id::AC4,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_OSQ => Id::OSQ,
            #[cfg(feature = "ffmpeg_7_0")]
            AV::AV_CODEC_ID_QOA => Id::QOA,
            #[cfg(feature = "ffmpeg_7_1")]
            AV::AV_CODEC_ID_LC3 => Id::LC3,
            #[cfg(feature = "ffmpeg_6_1")]
            AV::AV_CODEC_ID_SMPTE_2038 => Id::SMPTE_2038,
            #[cfg(feature = "ffmpeg_7_1")]
            AV::AV_CODEC_ID_LCEVC => Id::LCEVC,

            #[cfg(feature = "non-exhaustive-enums")]
            _ => unimplemented!(),
        }
    }
}

impl From<Id> for AVCodecID {
    fn from(value: Id) -> AVCodecID {
        match value {
            Id::None => Self::AV_CODEC_ID_NONE,

            /* video codecs */
            Id::MPEG1VIDEO => Self::AV_CODEC_ID_MPEG1VIDEO,
            Id::MPEG2VIDEO => Self::AV_CODEC_ID_MPEG2VIDEO,
            #[cfg(all(feature = "ff_api_xvmc", not(feature = "ffmpeg_5_0")))]
            Id::MPEG2VIDEO_XVMC => Self::AV_CODEC_ID_MPEG2VIDEO_XVMC,
            Id::H261 => Self::AV_CODEC_ID_H261,
            Id::H263 => Self::AV_CODEC_ID_H263,
            Id::RV10 => Self::AV_CODEC_ID_RV10,
            Id::RV20 => Self::AV_CODEC_ID_RV20,
            Id::MJPEG => Self::AV_CODEC_ID_MJPEG,
            Id::MJPEGB => Self::AV_CODEC_ID_MJPEGB,
            Id::LJPEG => Self::AV_CODEC_ID_LJPEG,
            Id::SP5X => Self::AV_CODEC_ID_SP5X,
            Id::JPEGLS => Self::AV_CODEC_ID_JPEGLS,
            Id::MPEG4 => Self::AV_CODEC_ID_MPEG4,
            Id::RAWVIDEO => Self::AV_CODEC_ID_RAWVIDEO,
            Id::MSMPEG4V1 => Self::AV_CODEC_ID_MSMPEG4V1,
            Id::MSMPEG4V2 => Self::AV_CODEC_ID_MSMPEG4V2,
            Id::MSMPEG4V3 => Self::AV_CODEC_ID_MSMPEG4V3,
            Id::WMV1 => Self::AV_CODEC_ID_WMV1,
            Id::WMV2 => Self::AV_CODEC_ID_WMV2,
            Id::H263P => Self::AV_CODEC_ID_H263P,
            Id::H263I => Self::AV_CODEC_ID_H263I,
            Id::FLV1 => Self::AV_CODEC_ID_FLV1,
            Id::SVQ1 => Self::AV_CODEC_ID_SVQ1,
            Id::SVQ3 => Self::AV_CODEC_ID_SVQ3,
            Id::DVVIDEO => Self::AV_CODEC_ID_DVVIDEO,
            Id::HUFFYUV => Self::AV_CODEC_ID_HUFFYUV,
            Id::CYUV => Self::AV_CODEC_ID_CYUV,
            Id::H264 => Self::AV_CODEC_ID_H264,
            Id::INDEO3 => Self::AV_CODEC_ID_INDEO3,
            Id::VP3 => Self::AV_CODEC_ID_VP3,
            Id::THEORA => Self::AV_CODEC_ID_THEORA,
            Id::ASV1 => Self::AV_CODEC_ID_ASV1,
            Id::ASV2 => Self::AV_CODEC_ID_ASV2,
            Id::FFV1 => Self::AV_CODEC_ID_FFV1,
            Id::XM4 => Self::AV_CODEC_ID_4XM,
            Id::VCR1 => Self::AV_CODEC_ID_VCR1,
            Id::CLJR => Self::AV_CODEC_ID_CLJR,
            Id::MDEC => Self::AV_CODEC_ID_MDEC,
            Id::ROQ => Self::AV_CODEC_ID_ROQ,
            Id::INTERPLAY_VIDEO => Self::AV_CODEC_ID_INTERPLAY_VIDEO,
            Id::XAN_WC3 => Self::AV_CODEC_ID_XAN_WC3,
            Id::XAN_WC4 => Self::AV_CODEC_ID_XAN_WC4,
            Id::RPZA => Self::AV_CODEC_ID_RPZA,
            Id::CINEPAK => Self::AV_CODEC_ID_CINEPAK,
            Id::WS_VQA => Self::AV_CODEC_ID_WS_VQA,
            Id::MSRLE => Self::AV_CODEC_ID_MSRLE,
            Id::MSVIDEO1 => Self::AV_CODEC_ID_MSVIDEO1,
            Id::IDCIN => Self::AV_CODEC_ID_IDCIN,
            Id::BPS8 => Self::AV_CODEC_ID_8BPS,
            Id::SMC => Self::AV_CODEC_ID_SMC,
            Id::FLIC => Self::AV_CODEC_ID_FLIC,
            Id::TRUEMOTION1 => Self::AV_CODEC_ID_TRUEMOTION1,
            Id::VMDVIDEO => Self::AV_CODEC_ID_VMDVIDEO,
            Id::MSZH => Self::AV_CODEC_ID_MSZH,
            Id::ZLIB => Self::AV_CODEC_ID_ZLIB,
            Id::QTRLE => Self::AV_CODEC_ID_QTRLE,
            Id::TSCC => Self::AV_CODEC_ID_TSCC,
            Id::ULTI => Self::AV_CODEC_ID_ULTI,
            Id::QDRAW => Self::AV_CODEC_ID_QDRAW,
            Id::VIXL => Self::AV_CODEC_ID_VIXL,
            Id::QPEG => Self::AV_CODEC_ID_QPEG,
            Id::PNG => Self::AV_CODEC_ID_PNG,
            Id::PPM => Self::AV_CODEC_ID_PPM,
            Id::PBM => Self::AV_CODEC_ID_PBM,
            Id::PGM => Self::AV_CODEC_ID_PGM,
            Id::PGMYUV => Self::AV_CODEC_ID_PGMYUV,
            Id::PAM => Self::AV_CODEC_ID_PAM,
            Id::FFVHUFF => Self::AV_CODEC_ID_FFVHUFF,
            Id::RV30 => Self::AV_CODEC_ID_RV30,
            Id::RV40 => Self::AV_CODEC_ID_RV40,
            Id::VC1 => Self::AV_CODEC_ID_VC1,
            Id::WMV3 => Self::AV_CODEC_ID_WMV3,
            Id::LOCO => Self::AV_CODEC_ID_LOCO,
            Id::WNV1 => Self::AV_CODEC_ID_WNV1,
            Id::AASC => Self::AV_CODEC_ID_AASC,
            Id::INDEO2 => Self::AV_CODEC_ID_INDEO2,
            Id::FRAPS => Self::AV_CODEC_ID_FRAPS,
            Id::TRUEMOTION2 => Self::AV_CODEC_ID_TRUEMOTION2,
            Id::BMP => Self::AV_CODEC_ID_BMP,
            Id::CSCD => Self::AV_CODEC_ID_CSCD,
            Id::MMVIDEO => Self::AV_CODEC_ID_MMVIDEO,
            Id::ZMBV => Self::AV_CODEC_ID_ZMBV,
            Id::AVS => Self::AV_CODEC_ID_AVS,
            Id::SMACKVIDEO => Self::AV_CODEC_ID_SMACKVIDEO,
            Id::NUV => Self::AV_CODEC_ID_NUV,
            Id::KMVC => Self::AV_CODEC_ID_KMVC,
            Id::FLASHSV => Self::AV_CODEC_ID_FLASHSV,
            Id::CAVS => Self::AV_CODEC_ID_CAVS,
            Id::JPEG2000 => Self::AV_CODEC_ID_JPEG2000,
            Id::VMNC => Self::AV_CODEC_ID_VMNC,
            Id::VP5 => Self::AV_CODEC_ID_VP5,
            Id::VP6 => Self::AV_CODEC_ID_VP6,
            Id::VP6F => Self::AV_CODEC_ID_VP6F,
            Id::TARGA => Self::AV_CODEC_ID_TARGA,
            Id::DSICINVIDEO => Self::AV_CODEC_ID_DSICINVIDEO,
            Id::TIERTEXSEQVIDEO => Self::AV_CODEC_ID_TIERTEXSEQVIDEO,
            Id::TIFF => Self::AV_CODEC_ID_TIFF,
            Id::GIF => Self::AV_CODEC_ID_GIF,
            Id::DXA => Self::AV_CODEC_ID_DXA,
            Id::DNXHD => Self::AV_CODEC_ID_DNXHD,
            Id::THP => Self::AV_CODEC_ID_THP,
            Id::SGI => Self::AV_CODEC_ID_SGI,
            Id::C93 => Self::AV_CODEC_ID_C93,
            Id::BETHSOFTVID => Self::AV_CODEC_ID_BETHSOFTVID,
            Id::PTX => Self::AV_CODEC_ID_PTX,
            Id::TXD => Self::AV_CODEC_ID_TXD,
            Id::VP6A => Self::AV_CODEC_ID_VP6A,
            Id::AMV => Self::AV_CODEC_ID_AMV,
            Id::VB => Self::AV_CODEC_ID_VB,
            Id::PCX => Self::AV_CODEC_ID_PCX,
            Id::SUNRAST => Self::AV_CODEC_ID_SUNRAST,
            Id::INDEO4 => Self::AV_CODEC_ID_INDEO4,
            Id::INDEO5 => Self::AV_CODEC_ID_INDEO5,
            Id::MIMIC => Self::AV_CODEC_ID_MIMIC,
            Id::RL2 => Self::AV_CODEC_ID_RL2,
            Id::ESCAPE124 => Self::AV_CODEC_ID_ESCAPE124,
            Id::DIRAC => Self::AV_CODEC_ID_DIRAC,
            Id::BFI => Self::AV_CODEC_ID_BFI,
            Id::CMV => Self::AV_CODEC_ID_CMV,
            Id::MOTIONPIXELS => Self::AV_CODEC_ID_MOTIONPIXELS,
            Id::TGV => Self::AV_CODEC_ID_TGV,
            Id::TGQ => Self::AV_CODEC_ID_TGQ,
            Id::TQI => Self::AV_CODEC_ID_TQI,
            Id::AURA => Self::AV_CODEC_ID_AURA,
            Id::AURA2 => Self::AV_CODEC_ID_AURA2,
            Id::V210X => Self::AV_CODEC_ID_V210X,
            Id::TMV => Self::AV_CODEC_ID_TMV,
            Id::V210 => Self::AV_CODEC_ID_V210,
            Id::DPX => Self::AV_CODEC_ID_DPX,
            Id::MAD => Self::AV_CODEC_ID_MAD,
            Id::FRWU => Self::AV_CODEC_ID_FRWU,
            Id::FLASHSV2 => Self::AV_CODEC_ID_FLASHSV2,
            Id::CDGRAPHICS => Self::AV_CODEC_ID_CDGRAPHICS,
            Id::R210 => Self::AV_CODEC_ID_R210,
            Id::ANM => Self::AV_CODEC_ID_ANM,
            Id::BINKVIDEO => Self::AV_CODEC_ID_BINKVIDEO,
            Id::IFF_ILBM => Self::AV_CODEC_ID_IFF_ILBM,
            Id::IFF_BYTERUN1 => Self::AV_CODEC_ID_IFF_ILBM,
            Id::KGV1 => Self::AV_CODEC_ID_KGV1,
            Id::YOP => Self::AV_CODEC_ID_YOP,
            Id::VP8 => Self::AV_CODEC_ID_VP8,
            Id::PICTOR => Self::AV_CODEC_ID_PICTOR,
            Id::ANSI => Self::AV_CODEC_ID_ANSI,
            Id::A64_MULTI => Self::AV_CODEC_ID_A64_MULTI,
            Id::A64_MULTI5 => Self::AV_CODEC_ID_A64_MULTI5,
            Id::R10K => Self::AV_CODEC_ID_R10K,
            Id::MXPEG => Self::AV_CODEC_ID_MXPEG,
            Id::LAGARITH => Self::AV_CODEC_ID_LAGARITH,
            Id::PRORES => Self::AV_CODEC_ID_PRORES,
            Id::JV => Self::AV_CODEC_ID_JV,
            Id::DFA => Self::AV_CODEC_ID_DFA,
            Id::WMV3IMAGE => Self::AV_CODEC_ID_WMV3IMAGE,
            Id::VC1IMAGE => Self::AV_CODEC_ID_VC1IMAGE,
            Id::UTVIDEO => Self::AV_CODEC_ID_UTVIDEO,
            Id::BMV_VIDEO => Self::AV_CODEC_ID_BMV_VIDEO,
            Id::VBLE => Self::AV_CODEC_ID_VBLE,
            Id::DXTORY => Self::AV_CODEC_ID_DXTORY,
            Id::V410 => Self::AV_CODEC_ID_V410,
            Id::XWD => Self::AV_CODEC_ID_XWD,
            Id::CDXL => Self::AV_CODEC_ID_CDXL,
            Id::XBM => Self::AV_CODEC_ID_XBM,
            Id::ZEROCODEC => Self::AV_CODEC_ID_ZEROCODEC,
            Id::MSS1 => Self::AV_CODEC_ID_MSS1,
            Id::MSA1 => Self::AV_CODEC_ID_MSA1,
            Id::TSCC2 => Self::AV_CODEC_ID_TSCC2,
            Id::MTS2 => Self::AV_CODEC_ID_MTS2,
            Id::CLLC => Self::AV_CODEC_ID_CLLC,
            Id::MSS2 => Self::AV_CODEC_ID_MSS2,
            Id::VP9 => Self::AV_CODEC_ID_VP9,
            Id::AIC => Self::AV_CODEC_ID_AIC,
            Id::ESCAPE130 => Self::AV_CODEC_ID_ESCAPE130,
            Id::G2M => Self::AV_CODEC_ID_G2M,
            Id::WEBP => Self::AV_CODEC_ID_WEBP,
            Id::HNM4_VIDEO => Self::AV_CODEC_ID_HNM4_VIDEO,
            Id::HEVC => Self::AV_CODEC_ID_HEVC,
            Id::H265 => Self::AV_CODEC_ID_HEVC,
            Id::FIC => Self::AV_CODEC_ID_FIC,
            Id::ALIAS_PIX => Self::AV_CODEC_ID_ALIAS_PIX,
            Id::BRENDER_PIX => Self::AV_CODEC_ID_BRENDER_PIX,
            Id::PAF_VIDEO => Self::AV_CODEC_ID_PAF_VIDEO,
            Id::EXR => Self::AV_CODEC_ID_EXR,
            Id::VP7 => Self::AV_CODEC_ID_VP7,
            Id::SANM => Self::AV_CODEC_ID_SANM,
            Id::SGIRLE => Self::AV_CODEC_ID_SGIRLE,
            Id::MVC1 => Self::AV_CODEC_ID_MVC1,
            Id::MVC2 => Self::AV_CODEC_ID_MVC2,
            Id::HQX => Self::AV_CODEC_ID_HQX,
            Id::TDSC => Self::AV_CODEC_ID_TDSC,
            Id::HQ_HQA => Self::AV_CODEC_ID_HQ_HQA,
            Id::HAP => Self::AV_CODEC_ID_HAP,
            Id::DDS => Self::AV_CODEC_ID_DDS,
            Id::DXV => Self::AV_CODEC_ID_DXV,
            Id::SCREENPRESSO => Self::AV_CODEC_ID_SCREENPRESSO,
            Id::RSCC => Self::AV_CODEC_ID_RSCC,

            Id::Y41P => Self::AV_CODEC_ID_Y41P,
            Id::AVRP => Self::AV_CODEC_ID_AVRP,
            Id::V012 => Self::AV_CODEC_ID_012V,
            Id::AVUI => Self::AV_CODEC_ID_AVUI,
            #[cfg(not(feature = "ffmpeg_7_0"))]
            Id::AYUV => Self::AV_CODEC_ID_AYUV,
            Id::TARGA_Y216 => Self::AV_CODEC_ID_TARGA_Y216,
            Id::V308 => Self::AV_CODEC_ID_V308,
            Id::V408 => Self::AV_CODEC_ID_V408,
            Id::YUV4 => Self::AV_CODEC_ID_YUV4,
            Id::AVRN => Self::AV_CODEC_ID_AVRN,
            Id::CPIA => Self::AV_CODEC_ID_CPIA,
            Id::XFACE => Self::AV_CODEC_ID_XFACE,
            Id::SNOW => Self::AV_CODEC_ID_SNOW,
            Id::SMVJPEG => Self::AV_CODEC_ID_SMVJPEG,
            Id::APNG => Self::AV_CODEC_ID_APNG,
            Id::DAALA => Self::AV_CODEC_ID_DAALA,
            Id::CFHD => Self::AV_CODEC_ID_CFHD,
            Id::TRUEMOTION2RT => Self::AV_CODEC_ID_TRUEMOTION2RT,
            Id::M101 => Self::AV_CODEC_ID_M101,
            Id::MAGICYUV => Self::AV_CODEC_ID_MAGICYUV,
            Id::SHEERVIDEO => Self::AV_CODEC_ID_SHEERVIDEO,
            Id::YLC => Self::AV_CODEC_ID_YLC,

            /* various PCM "codecs" */
            Id::PCM_S16LE => Self::AV_CODEC_ID_PCM_S16LE,
            Id::PCM_S16BE => Self::AV_CODEC_ID_PCM_S16BE,
            Id::PCM_U16LE => Self::AV_CODEC_ID_PCM_U16LE,
            Id::PCM_U16BE => Self::AV_CODEC_ID_PCM_U16BE,
            Id::PCM_S8 => Self::AV_CODEC_ID_PCM_S8,
            Id::PCM_U8 => Self::AV_CODEC_ID_PCM_U8,
            Id::PCM_MULAW => Self::AV_CODEC_ID_PCM_MULAW,
            Id::PCM_ALAW => Self::AV_CODEC_ID_PCM_ALAW,
            Id::PCM_S32LE => Self::AV_CODEC_ID_PCM_S32LE,
            Id::PCM_S32BE => Self::AV_CODEC_ID_PCM_S32BE,
            Id::PCM_U32LE => Self::AV_CODEC_ID_PCM_U32LE,
            Id::PCM_U32BE => Self::AV_CODEC_ID_PCM_U32BE,
            Id::PCM_S24LE => Self::AV_CODEC_ID_PCM_S24LE,
            Id::PCM_S24BE => Self::AV_CODEC_ID_PCM_S24BE,
            Id::PCM_U24LE => Self::AV_CODEC_ID_PCM_U24LE,
            Id::PCM_U24BE => Self::AV_CODEC_ID_PCM_U24BE,
            Id::PCM_S24DAUD => Self::AV_CODEC_ID_PCM_S24DAUD,
            Id::PCM_ZORK => Self::AV_CODEC_ID_PCM_ZORK,
            Id::PCM_S16LE_PLANAR => Self::AV_CODEC_ID_PCM_S16LE_PLANAR,
            Id::PCM_DVD => Self::AV_CODEC_ID_PCM_DVD,
            Id::PCM_F32BE => Self::AV_CODEC_ID_PCM_F32BE,
            Id::PCM_F32LE => Self::AV_CODEC_ID_PCM_F32LE,
            Id::PCM_F64BE => Self::AV_CODEC_ID_PCM_F64BE,
            Id::PCM_F64LE => Self::AV_CODEC_ID_PCM_F64LE,
            Id::PCM_BLURAY => Self::AV_CODEC_ID_PCM_BLURAY,
            Id::PCM_LXF => Self::AV_CODEC_ID_PCM_LXF,
            Id::S302M => Self::AV_CODEC_ID_S302M,
            Id::PCM_S8_PLANAR => Self::AV_CODEC_ID_PCM_S8_PLANAR,
            Id::PCM_S24LE_PLANAR => Self::AV_CODEC_ID_PCM_S24LE_PLANAR,
            Id::PCM_S32LE_PLANAR => Self::AV_CODEC_ID_PCM_S32LE_PLANAR,
            Id::PCM_S16BE_PLANAR => Self::AV_CODEC_ID_PCM_S16BE_PLANAR,

            Id::PCM_S64LE => Self::AV_CODEC_ID_PCM_S64LE,
            Id::PCM_S64BE => Self::AV_CODEC_ID_PCM_S64BE,

            /* various ADPCM codecs */
            Id::ADPCM_IMA_QT => Self::AV_CODEC_ID_ADPCM_IMA_QT,
            Id::ADPCM_IMA_WAV => Self::AV_CODEC_ID_ADPCM_IMA_WAV,
            Id::ADPCM_IMA_DK3 => Self::AV_CODEC_ID_ADPCM_IMA_DK3,
            Id::ADPCM_IMA_DK4 => Self::AV_CODEC_ID_ADPCM_IMA_DK4,
            Id::ADPCM_IMA_WS => Self::AV_CODEC_ID_ADPCM_IMA_WS,
            Id::ADPCM_IMA_SMJPEG => Self::AV_CODEC_ID_ADPCM_IMA_SMJPEG,
            Id::ADPCM_MS => Self::AV_CODEC_ID_ADPCM_MS,
            Id::ADPCM_4XM => Self::AV_CODEC_ID_ADPCM_4XM,
            Id::ADPCM_XA => Self::AV_CODEC_ID_ADPCM_XA,
            Id::ADPCM_ADX => Self::AV_CODEC_ID_ADPCM_ADX,
            Id::ADPCM_EA => Self::AV_CODEC_ID_ADPCM_EA,
            Id::ADPCM_G726 => Self::AV_CODEC_ID_ADPCM_G726,
            Id::ADPCM_CT => Self::AV_CODEC_ID_ADPCM_CT,
            Id::ADPCM_SWF => Self::AV_CODEC_ID_ADPCM_SWF,
            Id::ADPCM_YAMAHA => Self::AV_CODEC_ID_ADPCM_YAMAHA,
            Id::ADPCM_SBPRO_4 => Self::AV_CODEC_ID_ADPCM_SBPRO_4,
            Id::ADPCM_SBPRO_3 => Self::AV_CODEC_ID_ADPCM_SBPRO_3,
            Id::ADPCM_SBPRO_2 => Self::AV_CODEC_ID_ADPCM_SBPRO_2,
            Id::ADPCM_THP => Self::AV_CODEC_ID_ADPCM_THP,
            Id::ADPCM_IMA_AMV => Self::AV_CODEC_ID_ADPCM_IMA_AMV,
            Id::ADPCM_EA_R1 => Self::AV_CODEC_ID_ADPCM_EA_R1,
            Id::ADPCM_EA_R3 => Self::AV_CODEC_ID_ADPCM_EA_R3,
            Id::ADPCM_EA_R2 => Self::AV_CODEC_ID_ADPCM_EA_R2,
            Id::ADPCM_IMA_EA_SEAD => Self::AV_CODEC_ID_ADPCM_IMA_EA_SEAD,
            Id::ADPCM_IMA_EA_EACS => Self::AV_CODEC_ID_ADPCM_IMA_EA_EACS,
            Id::ADPCM_EA_XAS => Self::AV_CODEC_ID_ADPCM_EA_XAS,
            Id::ADPCM_EA_MAXIS_XA => Self::AV_CODEC_ID_ADPCM_EA_MAXIS_XA,
            Id::ADPCM_IMA_ISS => Self::AV_CODEC_ID_ADPCM_IMA_ISS,
            Id::ADPCM_G722 => Self::AV_CODEC_ID_ADPCM_G722,
            Id::ADPCM_IMA_APC => Self::AV_CODEC_ID_ADPCM_IMA_APC,
            Id::ADPCM_VIMA => Self::AV_CODEC_ID_ADPCM_VIMA,

            Id::ADPCM_AFC => Self::AV_CODEC_ID_ADPCM_AFC,
            Id::ADPCM_IMA_OKI => Self::AV_CODEC_ID_ADPCM_IMA_OKI,
            Id::ADPCM_DTK => Self::AV_CODEC_ID_ADPCM_DTK,
            Id::ADPCM_IMA_RAD => Self::AV_CODEC_ID_ADPCM_IMA_RAD,
            Id::ADPCM_G726LE => Self::AV_CODEC_ID_ADPCM_G726LE,
            Id::ADPCM_THP_LE => Self::AV_CODEC_ID_ADPCM_THP_LE,
            Id::ADPCM_PSX => Self::AV_CODEC_ID_ADPCM_PSX,
            Id::ADPCM_AICA => Self::AV_CODEC_ID_ADPCM_AICA,
            Id::ADPCM_IMA_DAT4 => Self::AV_CODEC_ID_ADPCM_IMA_DAT4,
            Id::ADPCM_MTAF => Self::AV_CODEC_ID_ADPCM_MTAF,

            /* AMR */
            Id::AMR_NB => Self::AV_CODEC_ID_AMR_NB,
            Id::AMR_WB => Self::AV_CODEC_ID_AMR_WB,

            /* RealAudio codecs*/
            Id::RA_144 => Self::AV_CODEC_ID_RA_144,
            Id::RA_288 => Self::AV_CODEC_ID_RA_288,

            /* various DPCM codecs */
            Id::ROQ_DPCM => Self::AV_CODEC_ID_ROQ_DPCM,
            Id::INTERPLAY_DPCM => Self::AV_CODEC_ID_INTERPLAY_DPCM,
            Id::XAN_DPCM => Self::AV_CODEC_ID_XAN_DPCM,
            Id::SOL_DPCM => Self::AV_CODEC_ID_SOL_DPCM,

            Id::SDX2_DPCM => Self::AV_CODEC_ID_SDX2_DPCM,

            /* audio codecs */
            Id::MP2 => Self::AV_CODEC_ID_MP2,
            Id::MP3 => Self::AV_CODEC_ID_MP3,
            Id::AAC => Self::AV_CODEC_ID_AAC,
            Id::AC3 => Self::AV_CODEC_ID_AC3,
            Id::DTS => Self::AV_CODEC_ID_DTS,
            Id::VORBIS => Self::AV_CODEC_ID_VORBIS,
            Id::DVAUDIO => Self::AV_CODEC_ID_DVAUDIO,
            Id::WMAV1 => Self::AV_CODEC_ID_WMAV1,
            Id::WMAV2 => Self::AV_CODEC_ID_WMAV2,
            Id::MACE3 => Self::AV_CODEC_ID_MACE3,
            Id::MACE6 => Self::AV_CODEC_ID_MACE6,
            Id::VMDAUDIO => Self::AV_CODEC_ID_VMDAUDIO,
            Id::FLAC => Self::AV_CODEC_ID_FLAC,
            Id::MP3ADU => Self::AV_CODEC_ID_MP3ADU,
            Id::MP3ON4 => Self::AV_CODEC_ID_MP3ON4,
            Id::SHORTEN => Self::AV_CODEC_ID_SHORTEN,
            Id::ALAC => Self::AV_CODEC_ID_ALAC,
            Id::WESTWOOD_SND1 => Self::AV_CODEC_ID_WESTWOOD_SND1,
            Id::GSM => Self::AV_CODEC_ID_GSM,
            Id::QDM2 => Self::AV_CODEC_ID_QDM2,
            Id::COOK => Self::AV_CODEC_ID_COOK,
            Id::TRUESPEECH => Self::AV_CODEC_ID_TRUESPEECH,
            Id::TTA => Self::AV_CODEC_ID_TTA,
            Id::SMACKAUDIO => Self::AV_CODEC_ID_SMACKAUDIO,
            Id::QCELP => Self::AV_CODEC_ID_QCELP,
            Id::WAVPACK => Self::AV_CODEC_ID_WAVPACK,
            Id::DSICINAUDIO => Self::AV_CODEC_ID_DSICINAUDIO,
            Id::IMC => Self::AV_CODEC_ID_IMC,
            Id::MUSEPACK7 => Self::AV_CODEC_ID_MUSEPACK7,
            Id::MLP => Self::AV_CODEC_ID_MLP,
            Id::GSM_MS => Self::AV_CODEC_ID_GSM_MS,
            Id::ATRAC3 => Self::AV_CODEC_ID_ATRAC3,
            Id::APE => Self::AV_CODEC_ID_APE,
            Id::NELLYMOSER => Self::AV_CODEC_ID_NELLYMOSER,
            Id::MUSEPACK8 => Self::AV_CODEC_ID_MUSEPACK8,
            Id::SPEEX => Self::AV_CODEC_ID_SPEEX,
            Id::WMAVOICE => Self::AV_CODEC_ID_WMAVOICE,
            Id::WMAPRO => Self::AV_CODEC_ID_WMAPRO,
            Id::WMALOSSLESS => Self::AV_CODEC_ID_WMALOSSLESS,
            Id::ATRAC3P => Self::AV_CODEC_ID_ATRAC3P,
            Id::EAC3 => Self::AV_CODEC_ID_EAC3,
            Id::SIPR => Self::AV_CODEC_ID_SIPR,
            Id::MP1 => Self::AV_CODEC_ID_MP1,
            Id::TWINVQ => Self::AV_CODEC_ID_TWINVQ,
            Id::TRUEHD => Self::AV_CODEC_ID_TRUEHD,
            Id::MP4ALS => Self::AV_CODEC_ID_MP4ALS,
            Id::ATRAC1 => Self::AV_CODEC_ID_ATRAC1,
            Id::BINKAUDIO_RDFT => Self::AV_CODEC_ID_BINKAUDIO_RDFT,
            Id::BINKAUDIO_DCT => Self::AV_CODEC_ID_BINKAUDIO_DCT,
            Id::AAC_LATM => Self::AV_CODEC_ID_AAC_LATM,
            Id::QDMC => Self::AV_CODEC_ID_QDMC,
            Id::CELT => Self::AV_CODEC_ID_CELT,
            Id::G723_1 => Self::AV_CODEC_ID_G723_1,
            Id::G729 => Self::AV_CODEC_ID_G729,
            Id::SVX_EXP8 => Self::AV_CODEC_ID_8SVX_EXP,
            Id::SVX_FIB8 => Self::AV_CODEC_ID_8SVX_FIB,
            Id::BMV_AUDIO => Self::AV_CODEC_ID_BMV_AUDIO,
            Id::RALF => Self::AV_CODEC_ID_RALF,
            Id::IAC => Self::AV_CODEC_ID_IAC,
            Id::ILBC => Self::AV_CODEC_ID_ILBC,
            Id::OPUS => Self::AV_CODEC_ID_OPUS,
            Id::COMFORT_NOISE => Self::AV_CODEC_ID_COMFORT_NOISE,
            Id::TAK => Self::AV_CODEC_ID_TAK,
            Id::METASOUND => Self::AV_CODEC_ID_METASOUND,
            Id::PAF_AUDIO => Self::AV_CODEC_ID_PAF_AUDIO,
            Id::ON2AVC => Self::AV_CODEC_ID_ON2AVC,
            Id::DSS_SP => Self::AV_CODEC_ID_DSS_SP,

            Id::CODEC2 => Self::AV_CODEC_ID_CODEC2,
            Id::FFWAVESYNTH => Self::AV_CODEC_ID_FFWAVESYNTH,
            Id::SONIC => Self::AV_CODEC_ID_SONIC,
            Id::SONIC_LS => Self::AV_CODEC_ID_SONIC_LS,
            Id::EVRC => Self::AV_CODEC_ID_EVRC,
            Id::SMV => Self::AV_CODEC_ID_SMV,
            Id::DSD_LSBF => Self::AV_CODEC_ID_DSD_LSBF,
            Id::DSD_MSBF => Self::AV_CODEC_ID_DSD_MSBF,
            Id::DSD_LSBF_PLANAR => Self::AV_CODEC_ID_DSD_LSBF_PLANAR,
            Id::DSD_MSBF_PLANAR => Self::AV_CODEC_ID_DSD_MSBF_PLANAR,
            Id::_4GV => Self::AV_CODEC_ID_4GV,
            Id::INTERPLAY_ACM => Self::AV_CODEC_ID_INTERPLAY_ACM,
            Id::XMA1 => Self::AV_CODEC_ID_XMA1,
            Id::XMA2 => Self::AV_CODEC_ID_XMA2,
            Id::DST => Self::AV_CODEC_ID_DST,

            /* subtitle codecs */
            Id::DVD_SUBTITLE => Self::AV_CODEC_ID_DVD_SUBTITLE,
            Id::DVB_SUBTITLE => Self::AV_CODEC_ID_DVB_SUBTITLE,
            Id::TEXT => Self::AV_CODEC_ID_TEXT,
            Id::XSUB => Self::AV_CODEC_ID_XSUB,
            Id::SSA => Self::AV_CODEC_ID_SSA,
            Id::MOV_TEXT => Self::AV_CODEC_ID_MOV_TEXT,
            Id::HDMV_PGS_SUBTITLE => Self::AV_CODEC_ID_HDMV_PGS_SUBTITLE,
            Id::DVB_TELETEXT => Self::AV_CODEC_ID_DVB_TELETEXT,
            Id::SRT => Self::AV_CODEC_ID_SRT,

            Id::MICRODVD => Self::AV_CODEC_ID_MICRODVD,
            Id::EIA_608 => Self::AV_CODEC_ID_EIA_608,
            Id::JACOSUB => Self::AV_CODEC_ID_JACOSUB,
            Id::SAMI => Self::AV_CODEC_ID_SAMI,
            Id::REALTEXT => Self::AV_CODEC_ID_REALTEXT,
            Id::STL => Self::AV_CODEC_ID_STL,
            Id::SUBVIEWER1 => Self::AV_CODEC_ID_SUBVIEWER1,
            Id::SUBVIEWER => Self::AV_CODEC_ID_SUBVIEWER,
            Id::SUBRIP => Self::AV_CODEC_ID_SUBRIP,
            Id::WEBVTT => Self::AV_CODEC_ID_WEBVTT,
            Id::MPL2 => Self::AV_CODEC_ID_MPL2,
            Id::VPLAYER => Self::AV_CODEC_ID_VPLAYER,
            Id::PJS => Self::AV_CODEC_ID_PJS,
            Id::ASS => Self::AV_CODEC_ID_ASS,
            Id::HDMV_TEXT_SUBTITLE => Self::AV_CODEC_ID_HDMV_TEXT_SUBTITLE,

            /* other specific kind of codecs (generally used for attachments) */
            Id::TTF => Self::AV_CODEC_ID_TTF,

            Id::SCTE_35 => Self::AV_CODEC_ID_SCTE_35,
            Id::BINTEXT => Self::AV_CODEC_ID_BINTEXT,
            Id::XBIN => Self::AV_CODEC_ID_XBIN,
            Id::IDF => Self::AV_CODEC_ID_IDF,
            Id::OTF => Self::AV_CODEC_ID_OTF,
            Id::SMPTE_KLV => Self::AV_CODEC_ID_SMPTE_KLV,
            Id::DVD_NAV => Self::AV_CODEC_ID_DVD_NAV,
            Id::TIMED_ID3 => Self::AV_CODEC_ID_TIMED_ID3,
            Id::BIN_DATA => Self::AV_CODEC_ID_BIN_DATA,

            Id::PROBE => Self::AV_CODEC_ID_PROBE,

            Id::MPEG2TS => Self::AV_CODEC_ID_MPEG2TS,
            Id::MPEG4SYSTEMS => Self::AV_CODEC_ID_MPEG4SYSTEMS,
            Id::FFMETADATA => Self::AV_CODEC_ID_FFMETADATA,
            Id::WRAPPED_AVFRAME => Self::AV_CODEC_ID_WRAPPED_AVFRAME,

            Id::PSD => Self::AV_CODEC_ID_PSD,
            Id::PIXLET => Self::AV_CODEC_ID_PIXLET,
            Id::SPEEDHQ => Self::AV_CODEC_ID_SPEEDHQ,
            Id::FMVC => Self::AV_CODEC_ID_FMVC,
            Id::CLEARVIDEO => Self::AV_CODEC_ID_CLEARVIDEO,
            Id::SCPR => Self::AV_CODEC_ID_SCPR,
            Id::XPM => Self::AV_CODEC_ID_XPM,
            Id::AV1 => Self::AV_CODEC_ID_AV1,
            Id::PCM_F16LE => Self::AV_CODEC_ID_PCM_F16LE,
            Id::PCM_F24LE => Self::AV_CODEC_ID_PCM_F24LE,
            Id::ATRAC3AL => Self::AV_CODEC_ID_ATRAC3AL,
            Id::ATRAC3PAL => Self::AV_CODEC_ID_ATRAC3PAL,

            Id::BITPACKED => Self::AV_CODEC_ID_BITPACKED,
            Id::MSCC => Self::AV_CODEC_ID_MSCC,
            Id::SRGC => Self::AV_CODEC_ID_SRGC,
            Id::SVG => Self::AV_CODEC_ID_SVG,
            Id::GDV => Self::AV_CODEC_ID_GDV,
            Id::FITS => Self::AV_CODEC_ID_FITS,
            Id::GREMLIN_DPCM => Self::AV_CODEC_ID_GREMLIN_DPCM,
            Id::DOLBY_E => Self::AV_CODEC_ID_DOLBY_E,

            Id::APTX => Self::AV_CODEC_ID_APTX,
            Id::APTX_HD => Self::AV_CODEC_ID_APTX_HD,
            Id::SBC => Self::AV_CODEC_ID_SBC,

            Id::AVS2 => Self::AV_CODEC_ID_AVS2,
            Id::IMM4 => Self::AV_CODEC_ID_IMM4,
            Id::PROSUMER => Self::AV_CODEC_ID_PROSUMER,
            Id::MWSC => Self::AV_CODEC_ID_MWSC,
            Id::WCMV => Self::AV_CODEC_ID_WCMV,
            Id::RASC => Self::AV_CODEC_ID_RASC,
            Id::PCM_VIDC => Self::AV_CODEC_ID_PCM_VIDC,
            Id::ATRAC9 => Self::AV_CODEC_ID_ATRAC9,
            Id::TTML => Self::AV_CODEC_ID_TTML,

            Id::HYMT => Self::AV_CODEC_ID_HYMT,
            Id::ARBC => Self::AV_CODEC_ID_ARBC,
            Id::AGM => Self::AV_CODEC_ID_AGM,
            Id::LSCR => Self::AV_CODEC_ID_LSCR,
            Id::VP4 => Self::AV_CODEC_ID_VP4,
            Id::ADPCM_AGM => Self::AV_CODEC_ID_ADPCM_AGM,
            Id::HCOM => Self::AV_CODEC_ID_HCOM,
            Id::ARIB_CAPTION => Self::AV_CODEC_ID_ARIB_CAPTION,

            #[cfg(feature = "ffmpeg_4_3")]
            Id::IMM5 => Self::AV_CODEC_ID_IMM5,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MVDV => Self::AV_CODEC_ID_MVDV,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MVHA => Self::AV_CODEC_ID_MVHA,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::CDTOONS => Self::AV_CODEC_ID_CDTOONS,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MV30 => Self::AV_CODEC_ID_MV30,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::NOTCHLC => Self::AV_CODEC_ID_NOTCHLC,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::PFM => Self::AV_CODEC_ID_PFM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_ARGO => Self::AV_CODEC_ID_ADPCM_ARGO,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_SSI => Self::AV_CODEC_ID_ADPCM_IMA_SSI,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_ZORK => Self::AV_CODEC_ID_ADPCM_ZORK,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_APM => Self::AV_CODEC_ID_ADPCM_IMA_APM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_ALP => Self::AV_CODEC_ID_ADPCM_IMA_ALP,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_MTF => Self::AV_CODEC_ID_ADPCM_IMA_MTF,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ADPCM_IMA_CUNNING => Self::AV_CODEC_ID_ADPCM_IMA_CUNNING,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::DERF_DPCM => Self::AV_CODEC_ID_DERF_DPCM,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::ACELP_KELVIN => Self::AV_CODEC_ID_ACELP_KELVIN,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::MPEGH_3D_AUDIO => Self::AV_CODEC_ID_MPEGH_3D_AUDIO,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::SIREN => Self::AV_CODEC_ID_SIREN,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::HCA => Self::AV_CODEC_ID_HCA,
            #[cfg(feature = "ffmpeg_4_3")]
            Id::EPG => Self::AV_CODEC_ID_EPG,

            #[cfg(feature = "ffmpeg_4_4")]
            Id::PGX => Self::AV_CODEC_ID_PGX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::AVS3 => Self::AV_CODEC_ID_AVS3,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::MSP2 => Self::AV_CODEC_ID_MSP2,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::VVC => Self::AV_CODEC_ID_VVC,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::MOBICLIP => Self::AV_CODEC_ID_MOBICLIP,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::PHOTOCD => Self::AV_CODEC_ID_PHOTOCD,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::IPU => Self::AV_CODEC_ID_IPU,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::ARGO => Self::AV_CODEC_ID_ARGO,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::CRI => Self::AV_CODEC_ID_CRI,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::SIMBIOSIS_IMX => Self::AV_CODEC_ID_SIMBIOSIS_IMX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::SGA_VIDEO => Self::AV_CODEC_ID_SGA_VIDEO,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::PCM_SGA => Self::AV_CODEC_ID_PCM_SGA,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::ADPCM_IMA_MOFLEX => Self::AV_CODEC_ID_ADPCM_IMA_MOFLEX,
            #[cfg(feature = "ffmpeg_4_4")]
            Id::FASTAUDIO => Self::AV_CODEC_ID_FASTAUDIO,

            #[cfg(feature = "ffmpeg_5_0")]
            Id::GEM => Self::AV_CODEC_ID_GEM,
            #[cfg(feature = "ffmpeg_5_0")]
            Id::ADPCM_IMA_ACORN => Self::AV_CODEC_ID_ADPCM_IMA_ACORN,
            #[cfg(feature = "ffmpeg_5_0")]
            Id::MSNSIREN => Self::AV_CODEC_ID_MSNSIREN,

            #[cfg(feature = "ffmpeg_5_1")]
            Id::VBN => Self::AV_CODEC_ID_VBN,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::JPEGXL => Self::AV_CODEC_ID_JPEGXL,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::QOI => Self::AV_CODEC_ID_QOI,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::PHM => Self::AV_CODEC_ID_PHM,
            #[cfg(feature = "ffmpeg_5_1")]
            Id::DFPWM => Self::AV_CODEC_ID_DFPWM,

            #[cfg(feature = "ffmpeg_6_0")]
            Id::RADIANCE_HDR => Self::AV_CODEC_ID_RADIANCE_HDR,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WBMP => Self::AV_CODEC_ID_WBMP,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::MEDIA100 => Self::AV_CODEC_ID_MEDIA100,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::VQC => Self::AV_CODEC_ID_VQC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::ADPCM_XMD => Self::AV_CODEC_ID_ADPCM_XMD,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WADY_DPCM => Self::AV_CODEC_ID_WADY_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::CBD2_DPCM => Self::AV_CODEC_ID_CBD2_DPCM,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::BONK => Self::AV_CODEC_ID_BONK,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::MISC4 => Self::AV_CODEC_ID_MISC4,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::APAC => Self::AV_CODEC_ID_APAC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::FTR => Self::AV_CODEC_ID_FTR,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::WAVARC => Self::AV_CODEC_ID_WAVARC,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::RKA => Self::AV_CODEC_ID_RKA,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::VNULL => Self::AV_CODEC_ID_VNULL,
            #[cfg(feature = "ffmpeg_6_0")]
            Id::ANULL => Self::AV_CODEC_ID_ANULL,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::PDV => Self::AV_CODEC_ID_PDV,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::EVC => Self::AV_CODEC_ID_EVC,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::RTV1 => Self::AV_CODEC_ID_RTV1,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::VMIX => Self::AV_CODEC_ID_VMIX,
            #[cfg(feature = "ffmpeg_7_0")]
            Id::LEAD => Self::AV_CODEC_ID_LEAD,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::AC4 => Self::AV_CODEC_ID_AC4,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::OSQ => Self::AV_CODEC_ID_OSQ,
            #[cfg(feature = "ffmpeg_7_0")]
            Id::QOA => Self::AV_CODEC_ID_QOA,
            #[cfg(feature = "ffmpeg_7_1")]
            Id::LC3 => Self::AV_CODEC_ID_LC3,
            #[cfg(feature = "ffmpeg_6_1")]
            Id::SMPTE_2038 => Self::AV_CODEC_ID_SMPTE_2038,
            #[cfg(feature = "ffmpeg_7_1")]
            Id::LCEVC => Self::AV_CODEC_ID_LCEVC,
        }
    }
}
